// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package promrw

import (
	"errors"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
)

// Constants for enum members

// Wrapper types for metrics with required attributes

// Metrics holds blitz's promrw self-telemetry instruments. Build one
// with NewMetrics from a caller-supplied MeterProvider so metrics can be routed
// to any provider (an embedding host's, or the process global).
type Metrics struct {
	promrwMeter metric.Meter

	// number of series per remote-write batch
	blitzOutputPrometheusRemoteWriteBatchSizeHistogram metric.Int64Histogram
	// latency of remote-write POST requests
	blitzOutputPrometheusRemoteWritePostLatencyHistogram metric.Float64Histogram
	// total number of remote-write POSTs that failed
	blitzOutputPrometheusRemoteWritePostsFailedCounter metric.Int64Counter
	// total number of series successfully posted
	blitzOutputPrometheusRemoteWriteSeriesSentCounter metric.Int64Counter
}

// NewMetrics builds the promrw instruments from mp. A nil mp falls
// back to the process-global MeterProvider, preserving standalone behavior.
func NewMetrics(mp metric.MeterProvider) (*Metrics, error) {
	if mp == nil {
		mp = otel.GetMeterProvider()
	}
	m := &Metrics{}
	var errs error

	m.promrwMeter = mp.Meter("promrw")

	blitzOutputPrometheusRemoteWriteBatchSizeHistogramRaw, err := m.promrwMeter.Int64Histogram(
		"blitz.output.prometheus_remote_write.batch_size",
		metric.WithDescription("number of series per remote-write batch"),
		metric.WithUnit("{series}"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusRemoteWriteBatchSizeHistogram = blitzOutputPrometheusRemoteWriteBatchSizeHistogramRaw

	blitzOutputPrometheusRemoteWritePostLatencyHistogramRaw, err := m.promrwMeter.Float64Histogram(
		"blitz.output.prometheus_remote_write.post_latency",
		metric.WithDescription("latency of remote-write POST requests"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusRemoteWritePostLatencyHistogram = blitzOutputPrometheusRemoteWritePostLatencyHistogramRaw

	blitzOutputPrometheusRemoteWritePostsFailedCounterRaw, err := m.promrwMeter.Int64Counter(
		"blitz.output.prometheus_remote_write.posts_failed",
		metric.WithDescription("total number of remote-write POSTs that failed"),
		metric.WithUnit("{post}"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusRemoteWritePostsFailedCounter = blitzOutputPrometheusRemoteWritePostsFailedCounterRaw

	blitzOutputPrometheusRemoteWriteSeriesSentCounterRaw, err := m.promrwMeter.Int64Counter(
		"blitz.output.prometheus_remote_write.series_sent",
		metric.WithDescription("total number of series successfully posted"),
		metric.WithUnit("{series}"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusRemoteWriteSeriesSentCounter = blitzOutputPrometheusRemoteWriteSeriesSentCounterRaw

	return m, errs
}
