// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package generator

import (
	"context"
	"errors"
	"fmt"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// Attribute name constants
const (
	attrErrorType     = "error_type"
	attrGeneratorType = "generator_type"
)

// ErrorTypeValue is the type of the error_type enum attribute
type ErrorTypeValue string

// Constants for enum members

const (
	ErrorTypeUnknown ErrorTypeValue = "unknown"
	ErrorTypeTimeout ErrorTypeValue = "timeout"
)

// Wrapper types for metrics with required attributes

// BlitzGeneratorEntriesCounterType wraps the blitz.generator.entries metric with type-safe required attributes
type BlitzGeneratorEntriesCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.generator.entries with required attributes
func (m BlitzGeneratorEntriesCounterType) Add(ctx context.Context, value int64, generatorType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrGeneratorType, generatorType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// BlitzGeneratorActiveWorkersGaugeType wraps the blitz.generator.active_workers metric with type-safe required attributes
type BlitzGeneratorActiveWorkersGaugeType struct {
	gauge metric.Int64Gauge
}

// Record records a value for blitz.generator.active_workers with required attributes
func (m BlitzGeneratorActiveWorkersGaugeType) Record(ctx context.Context, value int64, generatorType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrGeneratorType, generatorType),
	))

	if len(opts) == 0 {
		m.gauge.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.gauge.Record(ctx, value, allOpts...)
	}
}

// BlitzGeneratorWriteErrorsCounterType wraps the blitz.generator.write_errors metric with type-safe required attributes
type BlitzGeneratorWriteErrorsCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.generator.write_errors with required attributes
func (m BlitzGeneratorWriteErrorsCounterType) Add(ctx context.Context, value int64, generatorType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrGeneratorType, generatorType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

var (
	generatorMeter = otel.Meter("generator")

	// BlitzGeneratorEntriesCounter tracks the total number of telemetry entries generated
	BlitzGeneratorEntriesCounter BlitzGeneratorEntriesCounterType

	// BlitzGeneratorActiveWorkersGauge tracks the number of active worker goroutines
	BlitzGeneratorActiveWorkersGauge BlitzGeneratorActiveWorkersGaugeType

	// BlitzGeneratorWriteErrorsCounter tracks the total number of write errors
	BlitzGeneratorWriteErrorsCounter BlitzGeneratorWriteErrorsCounterType

	// error_type
	AttrErrorTypeUnknown = attribute.String(attrErrorType, string(ErrorTypeUnknown))
	AttrErrorTypeTimeout = attribute.String(attrErrorType, string(ErrorTypeTimeout))
)

func init() {
	var err, errs error

	blitzGeneratorEntriesCounterRaw, err := generatorMeter.Int64Counter(
		"blitz.generator.entries",
		metric.WithDescription("total number of telemetry entries generated"),
		metric.WithUnit("{entry}"),
	)
	errs = errors.Join(errs, err)
	BlitzGeneratorEntriesCounter = BlitzGeneratorEntriesCounterType{counter: blitzGeneratorEntriesCounterRaw}

	blitzGeneratorActiveWorkersGaugeRaw, err := generatorMeter.Int64Gauge(
		"blitz.generator.active_workers",
		metric.WithDescription("number of active worker goroutines"),
		metric.WithUnit("{worker}"),
	)
	errs = errors.Join(errs, err)
	BlitzGeneratorActiveWorkersGauge = BlitzGeneratorActiveWorkersGaugeType{gauge: blitzGeneratorActiveWorkersGaugeRaw}

	blitzGeneratorWriteErrorsCounterRaw, err := generatorMeter.Int64Counter(
		"blitz.generator.write_errors",
		metric.WithDescription("total number of write errors"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	BlitzGeneratorWriteErrorsCounter = BlitzGeneratorWriteErrorsCounterType{counter: blitzGeneratorWriteErrorsCounterRaw}

	if errs != nil {
		panic(fmt.Sprintf("Initialize generator metrics: %s", errs))
	}
}
