// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package generator

import (
	"context"
	"errors"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// Attribute name constants
const (
	attrErrorType     = "error_type"
	attrGeneratorType = "generator_type"
)

// error_typeValue is the type of the error_type enum attribute
type errorTypeValue string

// Constants for enum members

const (
	errorTypeUnknown errorTypeValue = "unknown"
	errorTypeTimeout errorTypeValue = "timeout"
)

// Wrapper types for metrics with required attributes

// blitzGeneratorActiveWorkersGaugeType wraps the blitz.generator.active_workers metric with type-safe required attributes
type blitzGeneratorActiveWorkersGaugeType struct {
	gauge metric.Int64Gauge
}

// Record records a value for blitz.generator.active_workers with required attributes
func (m blitzGeneratorActiveWorkersGaugeType) Record(ctx context.Context, value int64, generatorType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrGeneratorType, generatorType),
	))

	if len(opts) == 0 {
		m.gauge.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.gauge.Record(ctx, value, allOpts...)
	}
}

// blitzGeneratorEntriesCounterType wraps the blitz.generator.entries metric with type-safe required attributes
type blitzGeneratorEntriesCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.generator.entries with required attributes
func (m blitzGeneratorEntriesCounterType) Add(ctx context.Context, value int64, generatorType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrGeneratorType, generatorType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// blitzGeneratorWriteErrorsCounterType wraps the blitz.generator.write_errors metric with type-safe required attributes
type blitzGeneratorWriteErrorsCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.generator.write_errors with required attributes
func (m blitzGeneratorWriteErrorsCounterType) Add(ctx context.Context, value int64, generatorType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrGeneratorType, generatorType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// Attribute value options (provider-independent)
var (
	attrErrorTypeUnknown = attribute.String(attrErrorType, string(errorTypeUnknown))
	attrErrorTypeTimeout = attribute.String(attrErrorType, string(errorTypeTimeout))
)

// Metrics holds blitz's generator self-telemetry instruments. Build one
// with NewMetrics from a caller-supplied MeterProvider so metrics can be routed
// to any provider (an embedding host's, or the process global).
type Metrics struct {
	generatorMeter metric.Meter

	// number of active worker goroutines
	BlitzGeneratorActiveWorkersGauge blitzGeneratorActiveWorkersGaugeType
	// total number of telemetry entries generated
	BlitzGeneratorEntriesCounter blitzGeneratorEntriesCounterType
	// total number of write errors
	BlitzGeneratorWriteErrorsCounter blitzGeneratorWriteErrorsCounterType
}

// NewMetrics builds the generator instruments from mp. A nil mp falls
// back to the process-global MeterProvider, preserving standalone behavior.
func NewMetrics(mp metric.MeterProvider) (*Metrics, error) {
	if mp == nil {
		mp = otel.GetMeterProvider()
	}
	m := &Metrics{}
	var errs error

	m.generatorMeter = mp.Meter("generator")

	BlitzGeneratorActiveWorkersGaugeRaw, err := m.generatorMeter.Int64Gauge(
		"blitz.generator.active_workers",
		metric.WithDescription("number of active worker goroutines"),
		metric.WithUnit("{worker}"),
	)
	errs = errors.Join(errs, err)
	m.BlitzGeneratorActiveWorkersGauge = blitzGeneratorActiveWorkersGaugeType{gauge: BlitzGeneratorActiveWorkersGaugeRaw}

	BlitzGeneratorEntriesCounterRaw, err := m.generatorMeter.Int64Counter(
		"blitz.generator.entries",
		metric.WithDescription("total number of telemetry entries generated"),
		metric.WithUnit("{entry}"),
	)
	errs = errors.Join(errs, err)
	m.BlitzGeneratorEntriesCounter = blitzGeneratorEntriesCounterType{counter: BlitzGeneratorEntriesCounterRaw}

	BlitzGeneratorWriteErrorsCounterRaw, err := m.generatorMeter.Int64Counter(
		"blitz.generator.write_errors",
		metric.WithDescription("total number of write errors"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	m.BlitzGeneratorWriteErrorsCounter = blitzGeneratorWriteErrorsCounterType{counter: BlitzGeneratorWriteErrorsCounterRaw}

	return m, errs
}
