version: 2
project_name: blitz

builds:
  - id: blitz
    main: ./cmd/blitz
    binary: blitz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    tags:
      - timetzdata
    ldflags:
      - -s -w

archives:
  - id: archive
    builds:
      - blitz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    wrap_in_directory: true
    files:
      - LICENSE

nfpms:
  - id: linux-packages
    package_name: blitz
    file_name_template: "{{ .ProjectName }}_{{ .Arch }}"
    homepage: https://github.com/observiq/blitz
    maintainer: Bindplane Team <support@bindplane.com>
    description: Blitz - a load generation tool for Bindplane managed collectors.
    vendor: Bindplane
    license: Apache-2.0
    formats:
      - deb
      - rpm
    builds:
      - blitz
    bindir: /usr/bin
    scripts:
      preinstall: package/scripts/preinstall.sh
      postinstall: package/scripts/postinstall.sh
      preremove: package/scripts/preremove.sh
      postremove: package/scripts/postremove.sh
    contents:
      - src: LICENSE
        dst: /usr/share/doc/blitz/LICENSE
      - src: package/config.yaml
        dst: /etc/blitz/config.yaml
        type: config
        file_info:
          mode: 0640
          owner: blitz
          group: blitz
      - src: package/blitz.service
        dst: /usr/lib/systemd/system/blitz.service
        file_info:
          mode: 0640
          owner: root
          group: root

dockers:
  - id: docker-amd64
    ids:
      - blitz
    goos: linux
    goarch: amd64
    dockerfile: package/Dockerfile
    use: buildx
    image_templates:
      - ghcr.io/observiq/blitz:{{ .Version }}-amd64
      - ghcr.io/observiq/blitz:{{ .Tag }}-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --build-arg=PROJECT_NAME={{ .ProjectName }}
      - --build-arg=VERSION={{ .Version }}
      - --build-arg=COMMIT_SHA={{ .FullCommit }}
  - id: docker-arm64
    ids:
      - blitz
    goos: linux
    goarch: arm64
    dockerfile: package/Dockerfile
    use: buildx
    image_templates:
      - ghcr.io/observiq/blitz:{{ .Version }}-arm64
      - ghcr.io/observiq/blitz:{{ .Tag }}-arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --build-arg=PROJECT_NAME={{ .ProjectName }}
      - --build-arg=VERSION={{ .Version }}
      - --build-arg=COMMIT_SHA={{ .FullCommit }}

docker_manifests:
  - name_template: ghcr.io/observiq/blitz:{{ .Version }}
    image_templates:
      - ghcr.io/observiq/blitz:{{ .Version }}-amd64
      - ghcr.io/observiq/blitz:{{ .Version }}-arm64
  - name_template: ghcr.io/observiq/blitz:latest
    image_templates:
      - ghcr.io/observiq/blitz:{{ .Tag }}-amd64
      - ghcr.io/observiq/blitz:{{ .Tag }}-arm64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github

