// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package output

import (
	"context"
	"errors"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// Attribute name constants
const (
	attrOutputType    = "output_type"
	attrTelemetryType = "telemetry_type"
)

// Constants for enum members

// Wrapper types for metrics with required attributes

// blitzOutputActiveWorkersGaugeType wraps the blitz.output.active_workers metric with type-safe required attributes
type blitzOutputActiveWorkersGaugeType struct {
	gauge metric.Int64Gauge
}

// Record records a value for blitz.output.active_workers with required attributes
func (m blitzOutputActiveWorkersGaugeType) Record(ctx context.Context, value int64, outputType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
	))

	if len(opts) == 0 {
		m.gauge.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.gauge.Record(ctx, value, allOpts...)
	}
}

// blitzOutputEntriesReceivedCounterType wraps the blitz.output.entries_received metric with type-safe required attributes
type blitzOutputEntriesReceivedCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.output.entries_received with required attributes
func (m blitzOutputEntriesReceivedCounterType) Add(ctx context.Context, value int64, outputType string, telemetryType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// blitzOutputEntryRateCounterType wraps the blitz.output.entry_rate metric with type-safe required attributes
type blitzOutputEntryRateCounterType struct {
	counter metric.Float64Counter
}

// Add records a value for blitz.output.entry_rate with required attributes
func (m blitzOutputEntryRateCounterType) Add(ctx context.Context, value float64, outputType string, telemetryType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// blitzOutputRequestLatencyHistogramType wraps the blitz.output.request_latency metric with type-safe required attributes
type blitzOutputRequestLatencyHistogramType struct {
	histogram metric.Float64Histogram
}

// Record records a value for blitz.output.request_latency with required attributes
func (m blitzOutputRequestLatencyHistogramType) Record(ctx context.Context, value float64, outputType string, telemetryType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.histogram.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.histogram.Record(ctx, value, allOpts...)
	}
}

// blitzOutputRequestSizeHistogramType wraps the blitz.output.request_size metric with type-safe required attributes
type blitzOutputRequestSizeHistogramType struct {
	histogram metric.Int64Histogram
}

// Record records a value for blitz.output.request_size with required attributes
func (m blitzOutputRequestSizeHistogramType) Record(ctx context.Context, value int64, outputType string, telemetryType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.histogram.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.histogram.Record(ctx, value, allOpts...)
	}
}

// blitzOutputSendErrorsCounterType wraps the blitz.output.send_errors metric with type-safe required attributes
type blitzOutputSendErrorsCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.output.send_errors with required attributes
func (m blitzOutputSendErrorsCounterType) Add(ctx context.Context, value int64, outputType string, telemetryType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// ObservableCallbacks defines the callback interface for observable metrics
type ObservableCallbacks interface {
	ObserveBlitzOutputQueueSize(ctx context.Context, observer metric.Int64Observer) error
}

// Metrics holds blitz's output self-telemetry instruments. Build one
// with NewMetrics from a caller-supplied MeterProvider so metrics can be routed
// to any provider (an embedding host's, or the process global).
type Metrics struct {
	outputMeter metric.Meter

	// number of active output worker goroutines
	BlitzOutputActiveWorkersGauge blitzOutputActiveWorkersGaugeType
	// total number of telemetry entries received by the output
	BlitzOutputEntriesReceivedCounter blitzOutputEntriesReceivedCounterType
	// rate of telemetry entries processed per second
	BlitzOutputEntryRateCounter blitzOutputEntryRateCounterType
	// latency of output requests
	BlitzOutputRequestLatencyHistogram blitzOutputRequestLatencyHistogramType
	// size of output requests in bytes
	BlitzOutputRequestSizeHistogram blitzOutputRequestSizeHistogramType
	// total number of send errors
	BlitzOutputSendErrorsCounter blitzOutputSendErrorsCounterType
}

// NewMetrics builds the output instruments from mp. A nil mp falls
// back to the process-global MeterProvider, preserving standalone behavior.
func NewMetrics(mp metric.MeterProvider) (*Metrics, error) {
	if mp == nil {
		mp = otel.GetMeterProvider()
	}
	m := &Metrics{}
	var errs error

	m.outputMeter = mp.Meter("output")

	BlitzOutputActiveWorkersGaugeRaw, err := m.outputMeter.Int64Gauge(
		"blitz.output.active_workers",
		metric.WithDescription("number of active output worker goroutines"),
		metric.WithUnit("{worker}"),
	)
	errs = errors.Join(errs, err)
	m.BlitzOutputActiveWorkersGauge = blitzOutputActiveWorkersGaugeType{gauge: BlitzOutputActiveWorkersGaugeRaw}

	BlitzOutputEntriesReceivedCounterRaw, err := m.outputMeter.Int64Counter(
		"blitz.output.entries_received",
		metric.WithDescription("total number of telemetry entries received by the output"),
		metric.WithUnit("{entry}"),
	)
	errs = errors.Join(errs, err)
	m.BlitzOutputEntriesReceivedCounter = blitzOutputEntriesReceivedCounterType{counter: BlitzOutputEntriesReceivedCounterRaw}

	BlitzOutputEntryRateCounterRaw, err := m.outputMeter.Float64Counter(
		"blitz.output.entry_rate",
		metric.WithDescription("rate of telemetry entries processed per second"),
		metric.WithUnit("{entry}/s"),
	)
	errs = errors.Join(errs, err)
	m.BlitzOutputEntryRateCounter = blitzOutputEntryRateCounterType{counter: BlitzOutputEntryRateCounterRaw}

	BlitzOutputRequestLatencyHistogramRaw, err := m.outputMeter.Float64Histogram(
		"blitz.output.request_latency",
		metric.WithDescription("latency of output requests"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	m.BlitzOutputRequestLatencyHistogram = blitzOutputRequestLatencyHistogramType{histogram: BlitzOutputRequestLatencyHistogramRaw}

	BlitzOutputRequestSizeHistogramRaw, err := m.outputMeter.Int64Histogram(
		"blitz.output.request_size",
		metric.WithDescription("size of output requests in bytes"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	m.BlitzOutputRequestSizeHistogram = blitzOutputRequestSizeHistogramType{histogram: BlitzOutputRequestSizeHistogramRaw}

	BlitzOutputSendErrorsCounterRaw, err := m.outputMeter.Int64Counter(
		"blitz.output.send_errors",
		metric.WithDescription("total number of send errors"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	m.BlitzOutputSendErrorsCounter = blitzOutputSendErrorsCounterType{counter: BlitzOutputSendErrorsCounterRaw}

	return m, errs
}

// InitObservable registers the observable instruments against callbacks. Call
// it once, after NewMetrics, from the component that owns the observed state.
func (m *Metrics) InitObservable(callbacks ObservableCallbacks) error {
	var err, errs error

	_, err = m.outputMeter.Int64ObservableGauge(
		"blitz.output.queue_size",
		metric.WithDescription("current number of entries in the output queue"),
		metric.WithUnit("{entry}"),
		metric.WithInt64Callback(callbacks.ObserveBlitzOutputQueueSize),
	)
	errs = errors.Join(errs, err)

	return errs
}
