// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package output

import (
	"context"
	"errors"
	"fmt"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// Attribute name constants
const (
	attrOutputType    = "output_type"
	attrTelemetryType = "telemetry_type"
)

// Wrapper types for metrics with required attributes

// BlitzOutputEntriesReceivedCounterType wraps the blitz.output.entries_received metric with type-safe required attributes
type BlitzOutputEntriesReceivedCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.output.entries_received with required attributes
func (m BlitzOutputEntriesReceivedCounterType) Add(ctx context.Context, value int64, outputType string, telemetryType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// BlitzOutputActiveWorkersGaugeType wraps the blitz.output.active_workers metric with type-safe required attributes
type BlitzOutputActiveWorkersGaugeType struct {
	gauge metric.Int64Gauge
}

// Record records a value for blitz.output.active_workers with required attributes
func (m BlitzOutputActiveWorkersGaugeType) Record(ctx context.Context, value int64, outputType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
	))

	if len(opts) == 0 {
		m.gauge.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.gauge.Record(ctx, value, allOpts...)
	}
}

// BlitzOutputEntryRateCounterType wraps the blitz.output.entry_rate metric with type-safe required attributes
type BlitzOutputEntryRateCounterType struct {
	counter metric.Float64Counter
}

// Add records a value for blitz.output.entry_rate with required attributes
func (m BlitzOutputEntryRateCounterType) Add(ctx context.Context, value float64, outputType string, telemetryType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// BlitzOutputRequestSizeHistogramType wraps the blitz.output.request_size metric with type-safe required attributes
type BlitzOutputRequestSizeHistogramType struct {
	histogram metric.Int64Histogram
}

// Record records a value for blitz.output.request_size with required attributes
func (m BlitzOutputRequestSizeHistogramType) Record(ctx context.Context, value int64, outputType string, telemetryType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.histogram.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.histogram.Record(ctx, value, allOpts...)
	}
}

// BlitzOutputRequestLatencyHistogramType wraps the blitz.output.request_latency metric with type-safe required attributes
type BlitzOutputRequestLatencyHistogramType struct {
	histogram metric.Float64Histogram
}

// Record records a value for blitz.output.request_latency with required attributes
func (m BlitzOutputRequestLatencyHistogramType) Record(ctx context.Context, value float64, outputType string, telemetryType string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.histogram.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.histogram.Record(ctx, value, allOpts...)
	}
}

// BlitzOutputSendErrorsCounterType wraps the blitz.output.send_errors metric with type-safe required attributes
type BlitzOutputSendErrorsCounterType struct {
	counter metric.Int64Counter
}

// Add records a value for blitz.output.send_errors with required attributes
func (m BlitzOutputSendErrorsCounterType) Add(ctx context.Context, value int64, outputType string, telemetryType string, opts ...metric.AddOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrOutputType, outputType),
		attribute.String(attrTelemetryType, telemetryType),
	))

	if len(opts) == 0 {
		m.counter.Add(ctx, value, attrs)
	} else {
		allOpts := append([]metric.AddOption{attrs}, opts...)
		m.counter.Add(ctx, value, allOpts...)
	}
}

// ObservableCallbacks defines the callback interface for observable metrics
type ObservableCallbacks interface {
	ObserveBlitzOutputQueueSize(ctx context.Context, observer metric.Int64Observer) error
}

var (
	outputMeter = otel.Meter("output")

	// BlitzOutputEntriesReceivedCounter tracks the total number of log entries received by the output
	BlitzOutputEntriesReceivedCounter BlitzOutputEntriesReceivedCounterType

	// BlitzOutputActiveWorkersGauge tracks the number of active output worker goroutines
	BlitzOutputActiveWorkersGauge BlitzOutputActiveWorkersGaugeType

	// BlitzOutputEntryRateCounter tracks the rate of log entries processed per second
	BlitzOutputEntryRateCounter BlitzOutputEntryRateCounterType

	// BlitzOutputRequestSizeHistogram tracks the size of output requests in bytes
	BlitzOutputRequestSizeHistogram BlitzOutputRequestSizeHistogramType

	// BlitzOutputRequestLatencyHistogram tracks the latency of output requests
	BlitzOutputRequestLatencyHistogram BlitzOutputRequestLatencyHistogramType

	// BlitzOutputSendErrorsCounter tracks the total number of send errors
	BlitzOutputSendErrorsCounter BlitzOutputSendErrorsCounterType
)

func init() {
	var err, errs error

	blitzOutputEntriesReceivedCounterRaw, err := outputMeter.Int64Counter(
		"blitz.output.entries_received",
		metric.WithDescription("total number of log entries received by the output"),
		metric.WithUnit("{entry}"),
	)
	errs = errors.Join(errs, err)
	BlitzOutputEntriesReceivedCounter = BlitzOutputEntriesReceivedCounterType{counter: blitzOutputEntriesReceivedCounterRaw}

	blitzOutputActiveWorkersGaugeRaw, err := outputMeter.Int64Gauge(
		"blitz.output.active_workers",
		metric.WithDescription("number of active output worker goroutines"),
		metric.WithUnit("{worker}"),
	)
	errs = errors.Join(errs, err)
	BlitzOutputActiveWorkersGauge = BlitzOutputActiveWorkersGaugeType{gauge: blitzOutputActiveWorkersGaugeRaw}

	blitzOutputEntryRateCounterRaw, err := outputMeter.Float64Counter(
		"blitz.output.entry_rate",
		metric.WithDescription("rate of log entries processed per second"),
		metric.WithUnit("{entry}/s"),
	)
	errs = errors.Join(errs, err)
	BlitzOutputEntryRateCounter = BlitzOutputEntryRateCounterType{counter: blitzOutputEntryRateCounterRaw}

	blitzOutputRequestSizeHistogramRaw, err := outputMeter.Int64Histogram(
		"blitz.output.request_size",
		metric.WithDescription("size of output requests in bytes"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	BlitzOutputRequestSizeHistogram = BlitzOutputRequestSizeHistogramType{histogram: blitzOutputRequestSizeHistogramRaw}

	blitzOutputRequestLatencyHistogramRaw, err := outputMeter.Float64Histogram(
		"blitz.output.request_latency",
		metric.WithDescription("latency of output requests"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	BlitzOutputRequestLatencyHistogram = BlitzOutputRequestLatencyHistogramType{histogram: blitzOutputRequestLatencyHistogramRaw}

	blitzOutputSendErrorsCounterRaw, err := outputMeter.Int64Counter(
		"blitz.output.send_errors",
		metric.WithDescription("total number of send errors"),
		metric.WithUnit("{error}"),
	)
	errs = errors.Join(errs, err)
	BlitzOutputSendErrorsCounter = BlitzOutputSendErrorsCounterType{counter: blitzOutputSendErrorsCounterRaw}

	if errs != nil {
		panic(fmt.Sprintf("Initialize output metrics: %s", errs))
	}
}

// InitObservableMetrics initializes observable metrics with the provided callbacks
func InitObservableMetrics(callbacks ObservableCallbacks) {
	var err, errs error

	_, err = outputMeter.Int64ObservableGauge(
		"blitz.output.queue_size",
		metric.WithDescription("current number of entries in the output queue"),
		metric.WithUnit("{entry}"),
		metric.WithInt64Callback(callbacks.ObserveBlitzOutputQueueSize),
	)
	errs = errors.Join(errs, err)

	if errs != nil {
		panic(fmt.Sprintf("Initialize output observable metrics: %s", errs))
	}
}
