// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package runtime

import (
	"context"
	"errors"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// Attribute name constants
const (
	attrModuleName = "module_name"
)

// Constants for enum members

// Wrapper types for metrics with required attributes

// blitzModuleStartupDurationHistogramType wraps the blitz.module.startup.duration metric with type-safe required attributes
type blitzModuleStartupDurationHistogramType struct {
	histogram metric.Float64Histogram
}

// Record records a value for blitz.module.startup.duration with required attributes
func (m blitzModuleStartupDurationHistogramType) Record(ctx context.Context, value float64, moduleName string, opts ...metric.RecordOption) {
	attrs := metric.WithAttributeSet(attribute.NewSet(
		attribute.String(attrModuleName, moduleName),
	))

	if len(opts) == 0 {
		m.histogram.Record(ctx, value, attrs)
	} else {
		allOpts := append([]metric.RecordOption{attrs}, opts...)
		m.histogram.Record(ctx, value, allOpts...)
	}
}

// Metrics holds blitz's runtime self-telemetry instruments. Build one
// with NewMetrics from a caller-supplied MeterProvider so metrics can be routed
// to any provider (an embedding host's, or the process global).
type Metrics struct {
	runtimeMeter metric.Meter

	// time to start a single module during session startup
	BlitzModuleStartupDurationHistogram blitzModuleStartupDurationHistogramType
	// time to start all modules in the session
	BlitzSessionStartupDurationHistogram metric.Float64Histogram
	// time from process start to the service running
	BlitzStartupDurationHistogram metric.Float64Histogram
}

// NewMetrics builds the runtime instruments from mp. A nil mp falls
// back to the process-global MeterProvider, preserving standalone behavior.
func NewMetrics(mp metric.MeterProvider) (*Metrics, error) {
	if mp == nil {
		mp = otel.GetMeterProvider()
	}
	m := &Metrics{}
	var errs error

	m.runtimeMeter = mp.Meter("runtime")

	BlitzModuleStartupDurationHistogramRaw, err := m.runtimeMeter.Float64Histogram(
		"blitz.module.startup.duration",
		metric.WithDescription("time to start a single module during session startup"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	m.BlitzModuleStartupDurationHistogram = blitzModuleStartupDurationHistogramType{histogram: BlitzModuleStartupDurationHistogramRaw}

	BlitzSessionStartupDurationHistogramRaw, err := m.runtimeMeter.Float64Histogram(
		"blitz.session.startup.duration",
		metric.WithDescription("time to start all modules in the session"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	m.BlitzSessionStartupDurationHistogram = BlitzSessionStartupDurationHistogramRaw

	BlitzStartupDurationHistogramRaw, err := m.runtimeMeter.Float64Histogram(
		"blitz.startup.duration",
		metric.WithDescription("time from process start to the service running"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	m.BlitzStartupDurationHistogram = BlitzStartupDurationHistogramRaw

	return m, errs
}
