// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package promscrape

import (
	"errors"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
)

// Constants for enum members

// Wrapper types for metrics with required attributes

// Metrics holds blitz's promscrape self-telemetry instruments. Build one
// with NewMetrics from a caller-supplied MeterProvider so metrics can be routed
// to any provider (an embedding host's, or the process global).
type Metrics struct {
	promscrapeMeter metric.Meter

	// size of the exposition body per scrape
	blitzOutputPrometheusScrapeExpositionBytesHistogram metric.Int64Histogram
	// latency of serving a scrape request
	blitzOutputPrometheusScrapeScrapeLatencyHistogram metric.Float64Histogram
	// total number of scrape requests served
	blitzOutputPrometheusScrapeScrapesCounter metric.Int64Counter
	// number of series exposed at the last scrape
	blitzOutputPrometheusScrapeSeriesExposedGauge metric.Int64Gauge
}

// NewMetrics builds the promscrape instruments from mp. A nil mp falls
// back to the process-global MeterProvider, preserving standalone behavior.
func NewMetrics(mp metric.MeterProvider) (*Metrics, error) {
	if mp == nil {
		mp = otel.GetMeterProvider()
	}
	m := &Metrics{}
	var errs error

	m.promscrapeMeter = mp.Meter("promscrape")

	blitzOutputPrometheusScrapeExpositionBytesHistogramRaw, err := m.promscrapeMeter.Int64Histogram(
		"blitz.output.prometheus_scrape.exposition_bytes",
		metric.WithDescription("size of the exposition body per scrape"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusScrapeExpositionBytesHistogram = blitzOutputPrometheusScrapeExpositionBytesHistogramRaw

	blitzOutputPrometheusScrapeScrapeLatencyHistogramRaw, err := m.promscrapeMeter.Float64Histogram(
		"blitz.output.prometheus_scrape.scrape_latency",
		metric.WithDescription("latency of serving a scrape request"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusScrapeScrapeLatencyHistogram = blitzOutputPrometheusScrapeScrapeLatencyHistogramRaw

	blitzOutputPrometheusScrapeScrapesCounterRaw, err := m.promscrapeMeter.Int64Counter(
		"blitz.output.prometheus_scrape.scrapes",
		metric.WithDescription("total number of scrape requests served"),
		metric.WithUnit("{scrape}"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusScrapeScrapesCounter = blitzOutputPrometheusScrapeScrapesCounterRaw

	blitzOutputPrometheusScrapeSeriesExposedGaugeRaw, err := m.promscrapeMeter.Int64Gauge(
		"blitz.output.prometheus_scrape.series_exposed",
		metric.WithDescription("number of series exposed at the last scrape"),
		metric.WithUnit("{series}"),
	)
	errs = errors.Join(errs, err)
	m.blitzOutputPrometheusScrapeSeriesExposedGauge = blitzOutputPrometheusScrapeSeriesExposedGaugeRaw

	return m, errs
}
