// DO NOT MODIFY: This code is autogenerated by "make generate-o11y".
// See templates/registry/go/metric.go.j2.

//nolint:unused,revive
package hec

import (
	"errors"
	"fmt"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
)

var (
	hecMeter = otel.Meter("hec")

	// number of entries per HEC batch
	blitzOutputHecBatchSizeHistogram metric.Int64Histogram

	// number of ACKs currently pending confirmation
	blitzOutputHecAckPendingGauge metric.Int64Gauge

	// total number of ACKs confirmed by the server
	blitzOutputHecAckConfirmedCounter metric.Int64Counter

	// total number of ACKs that expired without confirmation
	blitzOutputHecAckExpiredCounter metric.Int64Counter

	// total number of batches retried due to ACK failure
	blitzOutputHecAckRetriedCounter metric.Int64Counter

	// total number of batches dropped after max retries
	blitzOutputHecAckDroppedCounter metric.Int64Counter

	// latency of ACK polling requests
	blitzOutputHecAckPollLatencyHistogram metric.Float64Histogram
)

func init() {
	var err, errs error

	blitzOutputHecBatchSizeHistogram, err = hecMeter.Int64Histogram(
		"blitz.output.hec.batch_size",
		metric.WithDescription("number of entries per HEC batch"),
		metric.WithUnit("{entry}"),
	)
	errs = errors.Join(errs, err)

	blitzOutputHecAckPendingGauge, err = hecMeter.Int64Gauge(
		"blitz.output.hec.ack_pending",
		metric.WithDescription("number of ACKs currently pending confirmation"),
		metric.WithUnit("{ack}"),
	)
	errs = errors.Join(errs, err)

	blitzOutputHecAckConfirmedCounter, err = hecMeter.Int64Counter(
		"blitz.output.hec.ack_confirmed",
		metric.WithDescription("total number of ACKs confirmed by the server"),
		metric.WithUnit("{ack}"),
	)
	errs = errors.Join(errs, err)

	blitzOutputHecAckExpiredCounter, err = hecMeter.Int64Counter(
		"blitz.output.hec.ack_expired",
		metric.WithDescription("total number of ACKs that expired without confirmation"),
		metric.WithUnit("{ack}"),
	)
	errs = errors.Join(errs, err)

	blitzOutputHecAckRetriedCounter, err = hecMeter.Int64Counter(
		"blitz.output.hec.ack_retried",
		metric.WithDescription("total number of batches retried due to ACK failure"),
		metric.WithUnit("{ack}"),
	)
	errs = errors.Join(errs, err)

	blitzOutputHecAckDroppedCounter, err = hecMeter.Int64Counter(
		"blitz.output.hec.ack_dropped",
		metric.WithDescription("total number of batches dropped after max retries"),
		metric.WithUnit("{ack}"),
	)
	errs = errors.Join(errs, err)

	blitzOutputHecAckPollLatencyHistogram, err = hecMeter.Float64Histogram(
		"blitz.output.hec.ack_poll_latency",
		metric.WithDescription("latency of ACK polling requests"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)

	if errs != nil {
		panic(fmt.Sprintf("Initialize hec metrics: %s", errs))
	}
}
