name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run ShellCheck
        run: |
          find package/scripts -type f -name "*.sh" -exec shellcheck {} +

  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: |
          go env
          go mod download

      - name: Install tools
        run: |
          make install-tools

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: |
          go test ./...

  gosec:
    name: Gosec
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run gosec
        run: |
          make security

  revive:
    name: Revive
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run revive
        run: |
          make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    env:
      cinc_package: https://packages.cinc.sh/files/stable/cinc-auditor/4.56.58/ubuntu/22.04/cinc-auditor_4.56.58-1_amd64.deb
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "v2.12.5"
          args: release --clean --skip=publish --skip=sign --skip=validate --snapshot --split
        env:
          GORELEASER_LICENSE: ${{ secrets.GORELEASER_KEY }}

      - name: Download CINC (Inspec)
        run: |
          mkdir -p /tmp/cinc
          curl -L -o /tmp/cinc/cinc.deb $cinc_package

      - name: Install CINC
        run: |
          sudo apt-get update
          sudo apt-get install -y -f /tmp/cinc/cinc.deb

      - name: Install package
        run: |
          sudo apt-get install -y -f ./dist/blitz_amd64.deb

      - name: Run install tests
        run: |
          sudo cinc-auditor exec package/inspec/install/package.rb

      - name: Uninstall package
        run: |
          sudo apt-get remove -y blitz

      - name: Run uninstall tests
        run: |
          sudo cinc-auditor exec package/inspec/remove/package.rb


